services:
  redis:
    image: redis
    container_name: hhcinema_redis
    ports:
      - "6379:6379" # Redis 기본 포트
    networks:
      - hh-cinema-network

  db:
    image: mysql:8.0
    container_name: hhcinema_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # 문자셋 설정
      TZ: Asia/Seoul
    command: --skip-character-set-client-handshake
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    networks:
      - hh-cinema-network

networks:
  hh-cinema-network:
    driver: bridge


# (프로젝트 루트 디렉토리로 이동 한 다음)
# Docker Compose Volumn 삭제
#  > docker-compose down -v

# Docker Compose 실행
#  > docker compose up -d

# Docker Compose 실행중 확인
#  > docker compose ps
#  NAME      IMAGE     COMMAND   SERVICE   CREATED   STATUS    PORTS

# > docker logs redis
# > docker logs hhcinema_db

